### ISSUE TITLE
Looks like you can replace latest state by wrong one, because all updates are scheduled to the Handler. 

### ISSUE THREAD

**Issue by adolgiy** [Mishkun/Puerh#1]
If you post updates from different threads to AndroidHandlerFeature, you can capture same state via `val state = currentState`, but the you will receive two different state after `reducer` is applied. Fix me, if i'm wrong.

See [AndroidHandlerFeature.kt#L25](https://github.com/Mishkun/Puerh/blob/e5b0e77eb76747aefa907a058c0d725c0b433d92/puerh-core/src/main/java/io/github/mishkun/puerh/core/AndroidHandlerFeature.kt#L25)

Solution: Capture current state from Runnable:
```kotlin
reduceHandler.post {
    val (newState, commands) = reducer(msg, currentState)
    callerThreadHandler.post {
        currentState = newState
        stateListeners.notifyAll(newState)
        commands.forEach { eff ->
            effListeners.notifyAll(eff)
        }
    }
}
```

**Comment by Mishkun** [comment]
Hi! Thank you for your interest in the project. I will research this issue asap. I am about to write tests for the core module, including stress tests to find out potential concurrency problems. Will include this case in tests and let you know about the results

**Comment by Mishkun** [comment]
I decided to remove AndroidHandlerFeature completely for now and try to find a substitution for its functionality (see #7 for details)
